### ISSUE TITLE
20.04 noetic compile issues

### ISSUE THREAD

**Issue by patripfr** [ANYbotics/pointmatcher-ros#21]
Hi,
when trying to compile on ubuntu 20.04 with ros noetic I am getting the following error:

/usr/bin/ld: cannot find -lBoost::thread 
/usr/bin/ld: cannot find -lBoost::program_options 
/usr/bin/ld: cannot find -lBoost::chrono 

When adding 
find_package(Boost COMPONENTS thread program_options chrono REQUIRED) 
to the CMakeLists.txt the issue does not appear. However, I saw that changes for noetic are already included in master, so I was wondering if I am missing something or if the line mentioned above should be added in a PR?

**Comment by YoshuaNava** [comment]
@patripfr Thank you for reporting this issue.

Can you describe what is your chain of dependencies? 

This issue has been addressed upstream, on our fork of libpointmatcher: https://github.com/ANYbotics/libpointmatcher/blob/master/CatkinBuild.cmake#L21

**Comment by patripfr** [comment]
Hi Yoshua,
I tried your fork but I am still getting errors that boost targets are not found

**Comment by YoshuaNava** [comment]
Can you further describe your build setup?

1. Build tool.
2. Whether you have any Debians for the packages in the pointmatcher_ros build chain.
3. When did this problem started happening?
4. Which repos are you using?

**Comment by patripfr** [comment]
After cleaning everything the error mentioned above indeed disappeared. However, now for all packages that I am using pointmatcher_ros in I get a linking error:

undefined reference to `PointMatcher<double>::DataPoints pointmatcher_ros::rosMsgToPointMatcherCloud<double>(sensor_msgs::PointCloud2_<std::allocator<void> > const&, bool)'
collect2: error: ld returned 1 exit status

I am using the anybotics fork of libpointmatcher and pointmatcher_ros both on master branch with catkin build
